name: code-qa

on:
  push:
    paths: ['**.py', 'pyproject.toml', '.github/workflows/ruff.yml']

jobs:
  code-qa:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install ruff
          pip install mypy

      - name: Lint with ruff
        run: ruff check .

      - name: Format with ruff
        run: ruff format . --check

      - name: Type checking with mypy
        run: mypy src --ignore-missing-imports
