name: Type checking

on:
  push:
    paths: ['**.py', 'pyproject.toml']

jobs:
  mypy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install mypy

      - name: Type checking with mypy
        run: mypy src --ignore-missing-imports
